//! Opt-in unstable non-final development facade. No scientific promotion.
//! Qualification-only modules remain outside the default/stable crate API.
#[path = "adaptive_evaluator.rs"]
pub mod adaptive_evaluator;
#[path = "adaptive_execution.rs"]
pub mod adaptive_execution;
#[path = "adaptive_inference.rs"]
pub mod adaptive_inference;
#[path = "adaptive_policies.rs"]
pub mod adaptive_policies;
#[path = "adaptive_rejections.rs"]
pub mod adaptive_rejections;
#[path = "adaptive_task_generators.rs"]
pub mod adaptive_task_generators;
#[path = "boolean_policy_carrier.rs"]
pub mod boolean_policy_carrier;
#[path = "boolean_policy_search.rs"]
pub mod boolean_policy_search;
#[path = "boolean_policy_search_c3.rs"]
pub mod boolean_policy_search_c3;
#[path = "boolean_policy_search_calibration.rs"]
pub mod boolean_policy_search_calibration;
#[path = "boolean_policy_sensitivity.rs"]
pub mod boolean_policy_sensitivity;
#[path = "boolean_policy_synthesis.rs"]
pub mod boolean_policy_synthesis;
#[path = "development_campaign.rs"]
pub mod development_campaign;
#[path = "tdi21_boolean_relational.rs"]
pub mod tdi21;
#[path = "tdi21_anf_search.rs"]
pub mod tdi21_anf_search;
#[path = "tdi21_anf_synthesis.rs"]
pub mod tdi21_anf_synthesis;
#[path = "tdi21_attention.rs"]
pub mod tdi21_attention;
#[path = "tdi21_distributional_objective.rs"]
pub mod tdi21_distributional_objective;
#[path = "tdi21_distributional_search.rs"]
pub mod tdi21_distributional_search;
#[path = "tdi21_evaluation.rs"]
pub mod tdi21_evaluation;
#[path = "tdi21_event_predicates.rs"]
pub mod tdi21_event_predicates;
#[path = "tdi21_freeze.rs"]
pub mod tdi21_freeze;
#[path = "tdi21_predicate_identifiability.rs"]
pub mod tdi21_predicate_identifiability;
#[path = "tdi21_provenance.rs"]
pub mod tdi21_provenance;
#[path = "tdi21_relational_address_search.rs"]
pub mod tdi21_relational_address_search;
#[path = "tdi21_relational_binding.rs"]
pub mod tdi21_relational_binding;
#[path = "tdi21_relational_learned.rs"]
pub mod tdi21_relational_learned;
#[path = "tdi21_relational_tasks.rs"]
pub mod tdi21_relational_tasks;
#[path = "tdi21_sequence_materializer.rs"]
pub mod tdi21_sequence_materializer;
#[path = "tdi21_stream.rs"]
pub mod tdi21_stream;
#[path = "tdi21_boolean_tasks.rs"]
pub mod tdi21_tasks;
#[path = "tdi22_eval.rs"]
pub mod tdi22_eval;
#[path = "tdi22_generator.rs"]
pub mod tdi22_generator;
#[path = "tdi22_torsor.rs"]
pub mod tdi22_torsor;
#[path = "tdi23_categorical.rs"]
pub mod tdi23_categorical;
#[path = "tdi23_ir.rs"]
pub mod tdi23_ir;
#[path = "tdi23_ir_equivalence.rs"]
pub mod tdi23_ir_equivalence;
#[path = "tdi23_ir_provenance.rs"]
pub mod tdi23_ir_provenance;
#[path = "tdi23_reduction.rs"]
pub mod tdi23_reduction;
#[path = "tdi23_rewrite.rs"]
pub mod tdi23_rewrite;
#[path = "tdi24_accounting.rs"]
pub mod tdi24_accounting;
#[path = "tdi24_attention.rs"]
pub mod tdi24_attention;
#[path = "tdi24_chiral.rs"]
pub mod tdi24_chiral;
#[path = "tdi24_tasks.rs"]
pub mod tdi24_tasks;
#[path = "tdi24_vector.rs"]
pub mod tdi24_vector;
#[path = "tdi25_torsor_chiral.rs"]
pub mod tdi25_torsor_chiral;
#[path = "tdi2_anti_unification.rs"]
pub mod tdi2_anti_unification;
#[path = "tdi2_baseline_contract.rs"]
pub mod tdi2_baseline_contract;
#[path = "tdi2_candidate_evidence.rs"]
pub mod tdi2_candidate_evidence;
#[path = "tdi2_candidate_identity.rs"]
pub mod tdi2_candidate_identity;
#[path = "tdi2_candidate_scoring.rs"]
pub mod tdi2_candidate_scoring;
#[path = "tdi2_candidate_selection.rs"]
pub mod tdi2_candidate_selection;
#[path = "tdi2_incremental_anti_unification.rs"]
pub mod tdi2_incremental_anti_unification;
#[path = "tdi2_induction_input.rs"]
pub mod tdi2_induction_input;
#[path = "tdi2_induction_provenance.rs"]
pub mod tdi2_induction_provenance;
#[path = "tdi2_induction_split.rs"]
pub mod tdi2_induction_split;
#[path = "tdi2_intuition.rs"]
pub mod tdi2_intuition;
#[path = "tdi2_intuition_ablations.rs"]
pub mod tdi2_intuition_ablations;
#[path = "tdi2_intuition_aggregation.rs"]
pub mod tdi2_intuition_aggregation;
#[path = "tdi2_intuition_analogy_tasks.rs"]
pub mod tdi2_intuition_analogy_tasks;
#[path = "tdi2_intuition_baselines.rs"]
pub mod tdi2_intuition_baselines;
#[path = "tdi2_intuition_calibration.rs"]
pub mod tdi2_intuition_calibration;
#[path = "tdi2_intuition_campaign.rs"]
pub mod tdi2_intuition_campaign;
#[path = "tdi2_intuition_consolidation.rs"]
pub mod tdi2_intuition_consolidation;
#[path = "tdi2_intuition_controls.rs"]
pub mod tdi2_intuition_controls;
#[path = "tdi2_intuition_cost.rs"]
pub mod tdi2_intuition_cost;
#[path = "tdi2_intuition_dedup.rs"]
pub mod tdi2_intuition_dedup;
#[path = "tdi2_intuition_encoder.rs"]
pub mod tdi2_intuition_encoder;
#[path = "tdi2_intuition_engine.rs"]
pub mod tdi2_intuition_engine;
#[path = "tdi2_intuition_evaluation.rs"]
pub mod tdi2_intuition_evaluation;
#[path = "tdi2_intuition_experience.rs"]
pub mod tdi2_intuition_experience;
#[path = "tdi2_intuition_inference.rs"]
pub mod tdi2_intuition_inference;
#[path = "tdi2_intuition_margin.rs"]
pub mod tdi2_intuition_margin;
#[path = "tdi2_intuition_matching.rs"]
pub mod tdi2_intuition_matching;
#[path = "tdi2_intuition_novelty.rs"]
pub mod tdi2_intuition_novelty;
#[path = "tdi2_intuition_predicates.rs"]
pub mod tdi2_intuition_predicates;
#[path = "tdi2_intuition_relations.rs"]
pub mod tdi2_intuition_relations;
#[path = "tdi2_intuition_reliability.rs"]
pub mod tdi2_intuition_reliability;
#[path = "tdi2_intuition_risk_coverage.rs"]
pub mod tdi2_intuition_risk_coverage;
#[path = "tdi2_intuition_scaling.rs"]
pub mod tdi2_intuition_scaling;
#[path = "tdi2_intuition_selection.rs"]
pub mod tdi2_intuition_selection;
#[path = "tdi2_intuition_store.rs"]
pub mod tdi2_intuition_store;
#[path = "tdi2_intuition_tasks.rs"]
pub mod tdi2_intuition_tasks;
#[path = "tdi2_intuition_temporal.rs"]
pub mod tdi2_intuition_temporal;
#[path = "tdi2_intuition_temporal_transfer.rs"]
pub mod tdi2_intuition_temporal_transfer;
#[path = "tdi2_intuition_trace.rs"]
pub mod tdi2_intuition_trace;
#[path = "tdi2_intuition_transfer.rs"]
pub mod tdi2_intuition_transfer;
#[path = "tdi2_intuition_transfer_baseline.rs"]
pub mod tdi2_intuition_transfer_baseline;
#[path = "tdi2_intuition_transfer_eval.rs"]
pub mod tdi2_intuition_transfer_eval;
#[path = "tdi2_intuition_transfer_tasks.rs"]
pub mod tdi2_intuition_transfer_tasks;
#[path = "tdi2_intuition_weight.rs"]
pub mod tdi2_intuition_weight;
#[path = "tdi2_numeric_thresholds.rs"]
pub mod tdi2_numeric_thresholds;
#[path = "tdi2_observation_graph.rs"]
pub mod tdi2_observation_graph;
#[path = "tdi2_pairwise_relations.rs"]
pub mod tdi2_pairwise_relations;
#[path = "tdi2_predicate_candidates.rs"]
pub mod tdi2_predicate_candidates;
#[path = "tdi2_predicate_discovery_controls.rs"]
pub mod tdi2_predicate_discovery_controls;
#[path = "tdi2_structural_terms.rs"]
pub mod tdi2_structural_terms;
#[path = "tdi2_template_induction.rs"]
pub mod tdi2_template_induction;
#[path = "tdi2_template_learning.rs"]
pub mod tdi2_template_learning;
#[path = "tdi2_analogical_mapping.rs"]
pub mod tdi2_analogical_mapping;
#[path = "tdi2_temporal_delta.rs"]
pub mod tdi2_temporal_delta;
