//! Opt-in unstable non-final development facade. No scientific promotion.
//! Qualification-only modules remain outside the default/stable crate API.
#[path = "adaptive_evaluator.rs"]
pub mod adaptive_evaluator;
#[path = "adaptive_execution.rs"]
pub mod adaptive_execution;
#[path = "adaptive_inference.rs"]
pub mod adaptive_inference;
#[path = "adaptive_policies.rs"]
pub mod adaptive_policies;
#[path = "adaptive_rejections.rs"]
pub mod adaptive_rejections;
#[path = "adaptive_task_generators.rs"]
pub mod adaptive_task_generators;
#[path = "boolean_policy_carrier.rs"]
pub mod boolean_policy_carrier;
#[path = "boolean_policy_search.rs"]
pub mod boolean_policy_search;
#[path = "boolean_policy_search_c3.rs"]
pub mod boolean_policy_search_c3;
#[path = "boolean_policy_search_calibration.rs"]
pub mod boolean_policy_search_calibration;
#[path = "boolean_policy_sensitivity.rs"]
pub mod boolean_policy_sensitivity;
#[path = "boolean_policy_synthesis.rs"]
pub mod boolean_policy_synthesis;
#[path = "development_campaign.rs"]
pub mod development_campaign;
#[path = "tdi21_boolean_relational.rs"]
pub mod tdi21;
#[path = "tdi21_anf_search.rs"]
pub mod tdi21_anf_search;
#[path = "tdi21_anf_synthesis.rs"]
pub mod tdi21_anf_synthesis;
#[path = "tdi21_attention.rs"]
pub mod tdi21_attention;
#[path = "tdi21_distributional_objective.rs"]
pub mod tdi21_distributional_objective;
#[path = "tdi21_distributional_search.rs"]
pub mod tdi21_distributional_search;
#[path = "tdi21_evaluation.rs"]
pub mod tdi21_evaluation;
#[path = "tdi21_event_predicates.rs"]
pub mod tdi21_event_predicates;
#[path = "tdi21_freeze.rs"]
pub mod tdi21_freeze;
#[path = "tdi21_predicate_identifiability.rs"]
pub mod tdi21_predicate_identifiability;
#[path = "tdi21_provenance.rs"]
pub mod tdi21_provenance;
#[path = "tdi21_sequence_materializer.rs"]
pub mod tdi21_sequence_materializer;
#[path = "tdi21_stream.rs"]
pub mod tdi21_stream;
#[path = "tdi21_boolean_tasks.rs"]
pub mod tdi21_tasks;
#[path = "tdi22_eval.rs"]
pub mod tdi22_eval;
#[path = "tdi22_torsor.rs"]
pub mod tdi22_torsor;
